--  ------------------------------------------- 
--  Generated by Enterprise Architect Ver. 4.01
--  Created On : domingo, 05 mayo, 2019 
--  DBMS       :  
--  ------------------------------------------- 

DROP TABLE Usuario;
DROP TABLE DetallePedido;
DROP TABLE Entrega;
DROP TABLE Administrativo;
DROP TABLE NotaVenta;
DROP TABLE Stock;
DROP TABLE Producto;
DROP TABLE Lote;
DROP TABLE Almacen;
DROP TABLE TipoProducto;
DROP TABLE Proveedor;
DROP TABLE Pedido;
DROP TABLE Cliente;
DROP TABLE TipoEntrega;

DROP SEQUENCE seq_cliente_id;
DROP SEQUENCE seq_proveedor_id;
DROP SEQUENCE seq_detalle_pedido_id;
DROP SEQUENCE seq_usuario_id;
DROP SEQUENCE seq_administrativo_id;
DROP SEQUENCE seq_nota_venta_id;
DROP SEQUENCE seq_stock_id;
DROP SEQUENCE seq_producto_id;
DROP SEQUENCE seq_lote_id;
DROP SEQUENCE seq_almacen_id;
DROP SEQUENCE seq_tipo_producto_id;
DROP SEQUENCE seq_pedido_id;
DROP SEQUENCE seq_tipo_entrega_id;
DROP SEQUENCE seq_entrega_id;


CREATE TABLE Administrativo
(
	id bigint default nextval('seq_administrativo_id'),
	codigo varchar(15) NOT NULL,
	nombre varchar(50) NOT NULL,
	telefono varchar(11) NOT NULL,
	estado varchar(10) NOT NULL,
	cargo varchar(15) NOT NULL,
	fecha_ingreso timestamp NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Cliente
(
	id bigint default nextval('seq_cliente_id'),
	codigo varchar(15) NOT NULL,
	nit int NOT NULL,
	nombre varchar(50) NOT NULL,
	telefono varchar(11) NOT NULL,
	estado varchar(10) NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Proveedor
(
	id bigint default nextval('seq_proveedor_id'),
	codigo varchar(15) NOT NULL,
	nombre varchar(50) NOT NULL,
    telefono varchar(11) NOT NULL,
    direccion varchar(20) NOT NULL,
	estado varchar(10) NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Usuario
(
	id bigint default nextval('seq_usuario_id'),
	usuario varchar(15) NOT NULL,
	contrasenia varchar(15) NOT NULL,
	estado varchar(10) NOT NULL,
	administrativoID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Pedido
(
	id bigint default nextval('seq_pedido_id'),
	codigo varchar(15) NOT NULL,
	fecha_registro timestamp NOT NULL,
	descripcion varchar(50) NOT NULL,
	estado varchar(10) NOT NULL,
	monto_total decimal(10,2) NOT NULL,
	clienteID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Almacen
(
	id bigint default nextval('seq_almacen_id'),
	codigo varchar(15) NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Lote
(
	id bigint default nextval('seq_lote_id'),
	codigo varchar(15) NOT NULL,
	fecha_ingreso timestamp NOT NULL,
	cantidad int NOT NULL,
	estado varchar(10) NOT NULL,
	almacenID bigint NOT NULL,
	proveedorID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE TipoProducto
(
	id bigint default nextval('seq_tipo_producto_id'),
	descripcion varchar(20) NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Producto
(
	id bigint default nextval('seq_producto_id'),
	codigo varchar(15) NOT NULL,
	marca varchar(15) NOT NULL,
	modelo varchar(15) NOT NULL,
	precio decimal(10,2) NOT NULL,
	costo decimal(10,2) NOT NULL,
	estado varchar(10) NOT NULL,
	loteID bigint NOT NULL,
	tipoProductoID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Stock
(
	id bigint default nextval('seq_stock_id'),
	cantidad int NOT NULL,
	almacenID bigint NOT NULL,
	productoID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE NotaVenta
(
	id bigint default nextval('seq_nota_venta_id'),
	codigo varchar(15) NOT NULL,
	fecha_emision timestamp NOT NULL,
	monto_total decimal(10,2),
	estado varchar(10) NOT NULL,
	pedidoID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE DetallePedido
(
    id bigint default nextval('seq_detalle_pedido_id'),
	cantidad int NOT NULL,
	descripcion varchar(50) NOT NULL,
	total decimal(10,2) NOT NULL,
	pedidoID bigint NOT NULL,
	productoID bigint NOT NULL,
	UNIQUE (id)
)
;

CREATE  TABLE TipoEntrega
(
	id bigint default nextval('seq_tipo_entrega_id'),
	descripcion varchar(20) NOT NULL,
	UNIQUE (id)
)
;

CREATE TABLE Entrega
(
	id bigint default nextval('seq_entrega_id'),
	codigo varchar(20) NOT NULL,
	fecha_registro timestamp NOT NULL,
	fecha_entrega timestamp NOT NULL,
	destino varchar(50) NOT NULL,
	estado varchar(10) NOT NULL,
	administrativoID bigint NOT NULL,
	notaVentaID bigint NOT NULL,
	tipoEntregaID bigint NOT NULL,
	UNIQUE (id)
) 
;

ALTER TABLE Cliente ADD CONSTRAINT PK_cliente
PRIMARY KEY (id)
;
ALTER TABLE Administrativo ADD CONSTRAINT PK_administrativo
PRIMARY KEY (id)
;
ALTER TABLE Proveedor ADD CONSTRAINT PK_proveedor
PRIMARY KEY (id)
;
ALTER TABLE Usuario ADD CONSTRAINT PK_usuario
PRIMARY KEY (id)
;
ALTER TABLE Pedido ADD CONSTRAINT PK_pedido
PRIMARY KEY (id)
;
ALTER TABLE Almacen ADD CONSTRAINT PK_almacen
PRIMARY KEY (id)
;
ALTER TABLE Lote ADD CONSTRAINT PK_lote
PRIMARY KEY (id)
;
ALTER TABLE TipoProducto ADD CONSTRAINT PK_tipo_producto
PRIMARY KEY (id)
;
ALTER TABLE Producto ADD CONSTRAINT PK_producto
PRIMARY KEY (id)
;
ALTER TABLE Stock ADD CONSTRAINT PK_stock
PRIMARY KEY (id)
;
ALTER TABLE NotaVenta ADD CONSTRAINT PK_nota_venta
PRIMARY KEY (id)
;
ALTER TABLE DetallePedido ADD CONSTRAINT PK_detalle_pedido
PRIMARY KEY (id)
;
ALTER TABLE TipoEntrega ADD CONSTRAINT PK_tipo_entrega
PRIMARY KEY (id)
;
ALTER TABLE Entrega ADD CONSTRAINT PK_entrega
PRIMARY KEY (id)
;


ALTER TABLE  Usuario ADD CONSTRAINT FK_usuario_administrativo
FOREIGN KEY (AdministrativoID) REFERENCES Administrativo (id)
;
ALTER TABLE  Pedido ADD CONSTRAINT FK_pedido_cliente
FOREIGN KEY (clienteID) REFERENCES Pedido (id)
;

ALTER TABLE NotaVenta ADD CONSTRAINT FK_nota_venta_pedido
FOREIGN KEY (pedidoID) REFERENCES Pedido (id)
;

ALTER TABLE  Entrega ADD CONSTRAINT FK_entrega_nota_venta
FOREIGN KEY (notaVentaID) REFERENCES NotaVenta (id)
;

ALTER TABLE  Entrega ADD CONSTRAINT FK_entrega_tipo_entrega
FOREIGN KEY (tipoEntregaID) REFERENCES TipoEntrega (id)
;

ALTER TABLE  Entrega ADD CONSTRAINT FK_entrega_administrativo
FOREIGN KEY (administrativoID) REFERENCES Administrativo (id)
;

ALTER TABLE  Lote ADD CONSTRAINT FK_lote_proveedor
FOREIGN KEY (proveedorID) REFERENCES Proveedor (id)
;

ALTER TABLE  Lote ADD CONSTRAINT FK_lote_almacen
FOREIGN KEY (almacenID) REFERENCES Almacen (id)
;
ALTER TABLE  Producto ADD CONSTRAINT FK_producto_lote
FOREIGN KEY (loteID) REFERENCES Lote (id)
;

ALTER TABLE  Producto ADD CONSTRAINT FK_producto_tipo_producto
FOREIGN KEY (tipoProductoID) REFERENCES Producto (id)
;

ALTER TABLE  Stock ADD CONSTRAINT FK_stock_almacen
FOREIGN KEY (almacenID) REFERENCES Almacen (id)
;

ALTER TABLE  Stock ADD CONSTRAINT FK_stock_producto
FOREIGN KEY (productoID) REFERENCES Producto (id)
;

ALTER TABLE  DetallePedido ADD CONSTRAINT FK_detalle_pedido_producto
FOREIGN KEY (productoID) REFERENCES Producto (id)
;
ALTER TABLE  DetallePedido ADD CONSTRAINT FK_detalle_pedido_pedido
FOREIGN KEY (pedidoID) REFERENCES Pedido (id)
;

----------------------------
-- sequence structure for seq_persona_id
------------------------------
create sequence seq_administrativo_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;


----------------------------
-- sequence structure for seq_cliente_id
------------------------------
create sequence seq_cliente_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_proveedor_id
------------------------------
create sequence seq_proveedor_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_pedido_id
------------------------------
create sequence seq_pedido_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_entrega_id
------------------------------
create sequence seq_entrega_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_tipo_entrega_id
------------------------------
create sequence seq_tipo_entrega_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_nota_venta_id
------------------------------
create sequence seq_nota_venta_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_usuario_id
------------------------------
create sequence seq_usuario_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_lote_id
------------------------------
create sequence seq_lote_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_almacen_id
------------------------------
create sequence seq_almacen_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_producto_id
------------------------------
create sequence seq_producto_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_detalle_pedido_id
------------------------------
create sequence seq_detalle_pedido_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_stock_id
------------------------------
create sequence seq_stock_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;

----------------------------
-- sequence structure for seq_tipo_producto_id
------------------------------
create sequence seq_tipo_producto_id
start with 1
increment by 1
maxvalue 999999999999999999
minvalue 1;